language: generic
branches:
  only:
    - master
env:
  DEV_REGISTRY=quay.io
  DOCKER_BUILD_FLAGS="--pull --no-cache"
services:
  - docker
sudo: required
install:
  - make bootstrap
script:
  - make test-style test-cover build docker-build
after_success:
  - bash <(curl -s https://codecov.io/bash)
