apiVersion: v1
kind: Secret
metadata:
  name: builder-ssh-private-keys
  labels:
    heritage: deis
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  ssh-host-rsa-key: "{{genPrivateKey "rsa" | b64enc}}"
  ssh-host-ecdsa-key: "{{genPrivateKey "ecdsa" | b64enc}}"
