name: builder
home: https://github.com/deis/builder
version: <Will be populated by the ci before publishing the chart>
description: Git server and application builder for Deis Workflow.
maintainers:
  - name: Deis Team
    email: engineering@deis.com
